### ISSUE TITLE
EC2 一覧に running 又は stopped 以外があるとあぷりが落ちる

### ISSUE THREAD

**Issue by inokappa** [inokappa/ec2ctrl#1]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12f6b16]

goroutine 1 [running]:
main.listInstances(0xc42000e0c8, 0x0, 0x0, 0x0)
        .../ec2ctrl.go:161 +0x296
main.main()
        ...ec2ctrl.go:294 +0x1df
```

**Comment by inokappa** [comment]
対応済みなので完了.
